methods/phe-cv19-site

- CMS/static/scss/all.scss
- CMS/static/scss/components/breadcrumbs.scss
- CMS/static/scss/components/download-button.scss
- CMS/static/scss/components/link-block.scss
- CMS/static/scss/components/tabbar.scss
- CMS/static/scss/global.scss
- CMS/static/scss/pages/resourceitempage.scss
- CMS/static/scss/pages/resourcepage.scss
- CMS/static/scss/variables.scss
- CMS/templates/contentPages/home_page.html
- CMS/templates/contentPages/landing_page.html
- CMS/templates/contentPages/overview_page.html
- CMS/templates/contentPages/resource_item_page.html
- CMS/templates/contentPages/resources_page.html
- CMS/templates/partials/breadcrumbs.html
- CMS/templates/partials/footer.html
- CMS/templates/partials/links-block.html
- CMS/templates/partials/nav.html
- CMS/templates/partials/resource_list_item.html
- CMS/templates/partials/tabbar.html
Cards, link-blocks and thumbnails weren't clickable across their whole face. These have been updated, focussable and given more emphatic focus states. 
I have also given focus states to missing buttons and included some minor updates to pass accessibility criteria
Check 'cards' on Homepage, LandingPage and ResourcesPage
Use axe to check accessibility tune up
> fully clickable cards and accessibility tune-up

- CMS/static/css/crc.css
- CMS/static/scss/pages/homepage.scss
- CMS/templates/partials/nav.html
Made footer/header focus and hover states accessible. 
Describe the steps required to test the changes.
> Bug fix/footer focus state

- CMS/templates/contentPages/home_page.html
- CMS/templates/contentPages/landing_page.html
- CMS/templates/contentPages/resources_page.html
Updated central white banner buttons
Pull and check banner buttons read "subscribe" and click through to the subscription url
> change message and link all center banner buttons

- CMS/templates/contentPages/landing_page.html
added the breadcrumb line on the campaign landing page
this used to be the homepage so didn't have breadcrumbs but now needs them
pull and check on each campaign landing page
> add breadcrumb line to landing page

- CMS/static/scss/global.scss
- CMS/templates/contentPages/home_page.html
- CMS/templates/contentPages/resource_item_page.html
- CMS/templates/contentPages/resources_page.html
Homepage.css is not loading properly due to MIMETYPE issues - shifted the content from there to the global scss file
> shift homepage scss to global file

- core/utils.py
Added metadata content type to the HTML upload files
Read the code
> specify the content type meta data for the files being exported

- CMS/static/scss/global.scss
Moved page scss to global because they weren't compiling as separate files
> all page scss moved to global

- core/templatetags/methods_tags.py
Stripped off all parameters as part of image request - these were causing image fails in prod
> strip query parameters even if this is not a restructure

- core/templatetags/methods_tags.py
> add https to images

- CMS/static/css/crc.css
- CMS/static/scss/subscription.scss
Changed front throughout to colour that meets accessibility requirements. 
Describe the steps required to test the changes.
> make color meet accessiblity requirements

- core/utils.py
Added more logging / error handling to s3 site deployment
Read the code
> error and missing config logging for s3 site deployment

- CMS/static/scss/global.scss
- CMS/templates/base.html
Create "Skip to main content" link
First tab on page will make "Skip to main content" link appear above the nav bar.
> add link and styling

- buildspec.yml
Added pre-build and post build phases to the buildspec file.
Changes were made to the buildspec.yml file where single phase approach was replaced to a pre build phase where codebuild logs into ECR and then the build where docker builds with a tag and post build action of pushing to the repo.
> added more phases to the build process

- CMS/settings/production.py
Changed the settings from Cloudflare to Couldfront because thats what we are using.
Check the settings are correct to the docs https://docs.wagtail.io/en/v2.6/reference/contrib/frontendcache.html#amazon-cloudfront
> switch cache settings to cloudfront

- CMS/templates/contentPages/resource_item_page.html
- core/templatetags/methods_tags.py
document id from database was getting added to the document link path - this removes it
> create s3 convert tag specific to documents

- CMS/static/scss/global.scss
- CMS/static/scss/pages/resourcepage.scss
Sidebar image was not scaling with viewport. I've set it to 100% of container width, seems to work ok.
Pull this branch and run the server, then go to the site resources page. Fiddle with viewport size in the dev tools, see if you think it works better now.
> fix sidebar image responsiveness

- CMS/templates/contentPages/home_page.html
small margin onto front page tiles
> add small margin to bottom of front page tile

- CMS/settings/production.py
Corrected the variable name to match the variable in the environment
> Release 0.1.1

- contentPages/models.py
Hardcode "Overview" and "Resources" subheading. 
"Overview" and "Resources" should appear as the default value.
> make default value for subheadings

- CMS/templates/partials/covid-alert.html
Separate commit for partial
Describe the steps required to test the changes.
> add banner partial

- README.md
- docs/data_reporting/DataReporting.md
- docs/data_reporting/downloads_export_report.sql
- docs/data_reporting/logs_import_script.sql
- docs/data_reporting/page_views_export_script.sql
Documentation and sql scripts for how we are producing the usage reports.
> add documentation and sql scripts for the usage reports

- CMS/static/js/main.js
- CMS/static/scss/subscription.scss
- subscription/templates/subscription/subscription_page.html
Added an error handler to submission API request to improve feedback to the user in the event of a failure.
try to subscribe for updates using an email address already registered. You should see an error message on the screen.
> add missing error handler to submission api call

- README.md
- docs/BranchingStrategy.md
- docs/CONTRIBUTING.md
- docs/CodeFormat.md
- docs/ContinuousIntegrationAndDeployment.md
- docs/LICENSE.md
- docs/Releases.md
- docs/TestingStrategy.md
- setup.cfg
Updated all the documentation files for the project
> update the documentation for the project

- robots.txt
Created a robots.txt file and disallowed crawling of static assets. 
Can be tested in a robots.txt tester to make sure it's skipping the static folder once it's deployed and live.
> Feature/create robots.txt

- CMS/templates/contentPages/asset_type_page.html
> add asset page

- data_reports/models.py
Creating release 1.3.2
Changes reviewed as features.
> Create release 1.3.2

- CMS/enums.py
- data_reports/scripts/downloads_export_script.sql
Added requested resource types to the list.
> add additional options to the resource types

- contentPages/migrations/0035_new_revision_for_draft_landing_pages.py
Changing the import method in the migration.
> change import method

- data_reports/models.py
Added a request token to the data report queries to stop them being started multiple times by each of the servers.
> add a request token to prevent multiple queries being started

- CMS/templates/contentPages/resources_page.html
Creating release 1.4.4
Changes reviewed as features
> Release 1.4.4

- CMS/static/js/fileupload.js
- CMS/templates/wagtaildocs/multiple/add.html
> modify file upload funtion to enforce filename pattern

- CMS/templates/contentPages/asset_type_page.html
I have changed the wording of "order by" to "sort by".
Run the code and see the difference on the resource list pages.
> changes wording of order by to sort by

- CMS/static/js/main.js
I have changed several of the error messages in the subscribe form in accordance with the Government Design System standards, e.g. removing "please" and clarifying the email address error message.
Run the code in development and visit the Subscribe page.
> clarifies error messages on subscribe form

- subscription/templates/subscription/subscription_page.html
I have enabled autocomplete on the subscribe page form, as required by the accessibility report.
Run the code in development and visit the Subscribe page.
> adds autocomlete attribute to form on subscribe page

- CMS/static/scss/crc.scss
- CMS/static/scss/subscription.scss
- subscription/templates/subscription/subscription_page.html
I have added padding between the input fields on the subscribe page so that it will be clearer to users which field is which, especially when there is an error message present.
Run the code in development and visit the Subscribe page.  Further test by submitting the form with errors.
> adds spacing between input fields on subscribe page

- CMS/static/scss/subscription.scss
I have reinstated a bracket that was mistakenly deleted in a previous PR.
> replaces missing bracket in scss file

- bin/container
- bin/coverage
- bin/lint
- bin/manage
- bin/shell
- bin/test
Fix bin commands to make them work in all directory names
> make the bin commands work for any directory name

- CMS/static/scss/components/download-button.scss
- CMS/static/scss/components/signup-button.scss
- CMS/static/scss/components/tabbar.scss
- CMS/static/scss/crc.scss
- CMS/static/scss/global.scss
- CMS/static/scss/reorder.scss
- CMS/static/scss/subscription.scss
- CMS/templates/partials/footer.html
- CMS/templates/partials/nav.html
I have added hover and focus state indicators to the PHE logo at the top of the page, in the nav bar.
Run the code in development and test the states.  For some reason in my browser the focus state is correct when forced using dev tools, but when I tab through it focuses on the wrong part of the nav bar, for some reason.  Would be grateful if you could review this.
> adds hover and focus state indicators to PHE logo in navbar

- CMS/static/scss/global.scss
When merging the https://github.com/methods/phe-cv19-site/pull/147 pull request, there was a missing bracket from the global.scss file.
Run the code
> missing bracket in global file
