core/wagtail_hooks.py
Added the document management button back to the admin nav
Log in to the CMS and the option 'Documents' should be on the side nav menu.
=> add document management back to the menu

CMS/templates/contentPages/overview_page.html, contentPages/models.py
Added an html template to render the overview page
Have left the breadcrumbs and tab bar nav section as hard coded - to be done properly across the site in a later update
Pull the code and test an overview page you create renders properly or review image below
=> add template html for overview

CMS/templates/contentPages/resource_item_page.html
I've completely removed the download button on the resource item page if no download is available. This is because they use resources just as a text placeholder to store links etc
=> completely remove download button if no download is available

CMS/static/js/main.js, contentPages/models.py
Add the document picker panel back to the resource item page editor.
In the CMS go the editor screen for a resource item page.
You should have the option to select the uploaded document you want to link to.
=> reenable the document picker on the resource item page

CMS/settings/production.py
Reverts methods/phe-cv19-site#48
As we now have logs coming out of the instances, this change is not required.
(and is currently breaking)
=> Revert "Feature/logging"

CMS/static/scss/global.scss, CMS/static/scss/pages/homepage.scss
Replaced the focus/hover border for buttons with a styled, border-like box shadow to avoid alignment issues. 
Recompile the scss and view the site - hovering and focus should look the same, but not cause aligntment problems.
ADDITIONAL!!
(sorry) my optionated reformatter also reformatted a bunch of stuff when I saved the files - sorry! Please add a comment if you want this undone.
=> replace button focus border with styled shadow

contentPages/models.py
Removed order_by line so that users can reorder items within the wagtail editor
=> wagtail already contains custom ordering code - remove order_by line

CMS/settings/base.py, CMS/templates/contentPages/home_page.html, CMS/templates/contentPages/landing_page.html, CMS/templates/contentPages/overview_page.html, CMS/templates/contentPages/resource_item_page.html, CMS/templates/contentPages/resources_page.html
compilescss was throwing errors for all content pages. It seems that while the django templating engine can cope with relative paths for include and extend statements i.e. `{% extends '../base.html'%}` other commands cannot
This PR registers CMS/templates as a templates directory in base.py. It then uses  `{% extends 'base.html'%}` without the relative reference for include and extends template syntax
Run `python manage.py compilescss` in the dev terminal.
Pull this code
Run again
Compare output
Check css is still as expected on the site
=> Fix issue with compilescss

requirements.txt
Upgraded the version of Wagtail due to potential security issue.
Run the CMS locally and go through testing all the CMS functionality.
=> upgrade the wagtail version to 2.8.1 (current latest)

contentPages/models.py
Only live asset pages will be displayed when a user selects an asset type tile.
=> only show live pages

CMS/static/scss/variables.scss
We have changed the colour of the <a> tags across the site in order to meet the 4.5 : 1 contrast ratio requirement.
Before:
After:
=> improves contrast on link tags across site

CMS/templates/contentPages/asset_type_page.html, CMS/templates/partials/covid-alert.html
We have added a role="banner" attribute to the covid alert div so that it has a landmark.  We have also removed the duplicate <main> element from the Type Category page.
Run the code in development and visit any page to check the banner, and any type category page to check the main element.
=> resolves issues with landmarks

CMS/templates/partials/resource_list_item.html
We have removed the title attribute from the resource list item div element, which was causing screen readers to stutter, as well as not corresponding to any visual text content in the div.
=> removes title attribute from div element in resource list item

CMS/static/scss/components/link-block.scss, CMS/static/scss/variables.scss
We have removed the opacity from the tiles on the campaign page, and changed the colour scheme for the title and main tile body using two new colour variables to keep it broadly in line with the rest of the site.
=> removes opacity on campaign page tiles

CMS/static/js/reorder.js, CMS/static/scss/reorder.scss
We have removed part of the sort button styling that was clashing with jquery and causing the page to jump on click.
Run the code in development and visit all-resources/posters or a campaign resources page and test the sort buttons.
=> stops page jumping when sort button is clicked

CMS/static/scss/base/_utilities.scss, CMS/static/scss/global.scss, CMS/templates/500.html, CMS/templates/base.html, CMS/templates/contentPages/resources_page.html, CMS/templates/partials/no-js.html, CMS/templates/search.html
Government websites often require content to be available when javascript is turned off. This is often done by having a no-js class on a top level tag which will be removed using a simple inline script if javascript is running. If javascript is not running the script doesn't run, the `no-js` class stays, and css can be used to make changes to the site.
PHE already had a `no-js` tag in it's `html` element but it was non-functional. This PR makes that functionality work and uses it to hide features that rely on javascript with the new `no-js-hidden` class
This review requires you to switch between javascript on and off. This is hidden somewhere in settings and there are plenty of Chrome extensions like "Quick Javascript Switcher" that can be useful
**With javascript turned on**
Check that …
=> add no-js functionality

contentPages/models.py, core/wagtail_hooks.py
We have manually set the attributes of each rich text input field to remove the option to add headings, as requested by PHE in our meeting yesterday.
Run the code and visit the different content upload pages of the CMS.
=> removes headings from rich text input fields

CMS/static/scss/crc.scss, CMS/static/scss/global.scss
We have slightly modified the navbar stylings to fix a bug where focus states were misaligned when the font was zoomed to 200%.
Run the code and visit any page in safari, zoom the font to 200% and tab through the nav bar.
=> fixes focus issue when zoomed in

CMS/static/scss/components/link-block.scss, CMS/static/scss/crc.scss, CMS/static/scss/global.scss
We have changed the height property to a min-height property of the Overview and Resource tiles on Campaign page to allow the tile text to be resized without cutting off the content. We also added some bottom padding on the background image to keep the same gap at the bottom and top with the tiles border while zooming.
Before:
After:
For this review is better to use the Safari browser because you can increase or decrease just the font size of the page and this is what is needed to review the changes.
=> allows font size adjustments on the overview and resource tiles without loss of content

CMS/static/scss/global.scss
We have added the overflow and text-overflow properties on the tile description section to let the user know that the full description is displayed on the next page.
Before:
After:
For this review is best to use the Safari browser in order to increase/decrease the font size.
=> description on tiles renders fully

CMS/static/scss/crc.scss, CMS/static/scss/global.scss
We have updated the header across site so that it adjusts its size when the text is zoomed in without overlapping with other elements.
Before:
After:
For this review is best to use the Safari browser in order to increase/decrease the font size.
=> stops the header to overlap with other elements across the site

CMS/static/scss/components/link-block.scss, CMS/static/scss/global.scss
We have fixed the jump issue of the tiles when in the hover or focus state (check the comment you left on https://github.com/methods/phe-cv19-site/pull/146 ).
Also we took out the outline that was showing up on Safari by default, when focusing on the <main> and the <a> tag elements on the same page.
The outline when in focus state on <a> and <main> tag elements:
Best to run the code in Safari, hover and tab through the page.
=> solves the tiles bobbing issue on hover and focus

contentPages/models.py
We have removed the blank="true" attribute from all necessary headings across the CMS, to avoid input errors resulting in empty heading tags in the future.
Run the code and explore the CMS content pages.
=> headings made compulsory in CMS

CMS/static/scss/components/link-block.scss
We have added a media query to the hover and focus states for the tiles so that they don't bob about when stacked.  There are still issues with the tiles altering the background image size when in hover state when the overview/resource text is long, but we think this is a marginal case.
Run the code and visit the campaign landing page, reduce the window so the tiles are stacked, and hover.
=> fixes tiles bobbing in hover state

CMS/static/scss/components/link-block.scss, CMS/static/scss/crc.scss
We have changed the border on the campaign page tiles to an outline to prevent the text from resizing, which was causing bobbing and resizing of the background image when in a focus/hover state and with a long overview/resource tile description text.
We have also changed the height property of the background image to min-height below 991px so that the image still extends under both tiles.
Visit the campaign page, add text to one of the tiles, and focus/hover over the tiles.  Reduce screen width to check the background image is resizing.
=> fixes border on tiles to prevent bobbing

requirements.txt
We have specified the version of psycopg being used in requirements.txt to avoid a "database connection isn't set to UTC" error.
Navigate to requirements.txt and view the file.  Run the code and check that the above error does not occur.
=> specifies psycopg version

CMS/templates/contentPages/asset_type_page.html, CMS/templates/contentPages/resources_page.html
We have modified the HTML in the resources_page and asset_type_page templates so that the resources are by default ordered newest first, rather than by most popular.  We have also swapped the button positions to reflect this, with the 'Newest' button now appearing on the left.
Run the code in development and visit both categories of resource page to check that the sort functionality is working as expected.
=> sets default sort to newest
